### ISSUE TITLE
IndexError: list index out of range in power.py

### ISSUE THREAD

**Issue by mikejmerchant** [AndrewLighten/fit-peaks#2]
Hi Andrew, Ive got a list index out of range error - any ideas how to resolve?

MacBook-Pro:fit-peaks-master mdehsmmxt$ python fitpeaks.py power > output.txt
Traceback (most recent call last):
  File "fitpeaks.py", line 77, in <module>
    main()
  File "fitpeaks.py", line 72, in main
    cli(None)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "fitpeaks.py", line 34, in do_power_report
    power_report(all)
  File "/Users/user/Dropbox (Personal)/MikeZwiftData/fit-peaks-master/power.py", line 286, in power_report
    _print_summary(max)
  File "/Users/user/Dropbox (Personal)/MikeZwiftData/fit-peaks-master/power.py", line 417, in _print_summary
    p120min_1 = (str(max["120min"][1]) if "120min" in max else "").rjust(4)
IndexError: list index out of range
--

Thanks,
Mike

**Comment by AndrewLighten** [comment]
I know this is a _really_ old issue, but it should be fixed by now. The problem is that it didn't cope if you didn't have two or more 120 minute exercises. It should cope with that now.
